// Approximate population-weighted centroids for major countries.
// Used for plotting concern dots on the world map and for the country selector.
export type Country = {
  code: string; // ISO-2
  name: string;
  lat: number;
  lon: number;
};

export const COUNTRIES: Country[] = [
  { code: "US", name: "United States", lat: 39.8, lon: -98.6 },
  { code: "CA", name: "Canada", lat: 56.1, lon: -106.3 },
  { code: "MX", name: "Mexico", lat: 23.6, lon: -102.5 },
  { code: "BR", name: "Brazil", lat: -14.2, lon: -51.9 },
  { code: "AR", name: "Argentina", lat: -38.4, lon: -63.6 },
  { code: "CL", name: "Chile", lat: -35.7, lon: -71.5 },
  { code: "CO", name: "Colombia", lat: 4.6, lon: -74.3 },
  { code: "PE", name: "Peru", lat: -9.2, lon: -75.0 },
  { code: "VE", name: "Venezuela", lat: 6.4, lon: -66.6 },
  { code: "GB", name: "United Kingdom", lat: 55.4, lon: -3.4 },
  { code: "IE", name: "Ireland", lat: 53.4, lon: -8.2 },
  { code: "FR", name: "France", lat: 46.2, lon: 2.2 },
  { code: "DE", name: "Germany", lat: 51.2, lon: 10.5 },
  { code: "ES", name: "Spain", lat: 40.5, lon: -3.7 },
  { code: "PT", name: "Portugal", lat: 39.4, lon: -8.2 },
  { code: "IT", name: "Italy", lat: 41.9, lon: 12.6 },
  { code: "NL", name: "Netherlands", lat: 52.1, lon: 5.3 },
  { code: "BE", name: "Belgium", lat: 50.5, lon: 4.5 },
  { code: "CH", name: "Switzerland", lat: 46.8, lon: 8.2 },
  { code: "AT", name: "Austria", lat: 47.5, lon: 14.6 },
  { code: "SE", name: "Sweden", lat: 60.1, lon: 18.6 },
  { code: "NO", name: "Norway", lat: 60.5, lon: 8.5 },
  { code: "DK", name: "Denmark", lat: 56.3, lon: 9.5 },
  { code: "FI", name: "Finland", lat: 61.9, lon: 25.7 },
  { code: "PL", name: "Poland", lat: 51.9, lon: 19.1 },
  { code: "CZ", name: "Czechia", lat: 49.8, lon: 15.5 },
  { code: "GR", name: "Greece", lat: 39.1, lon: 21.8 },
  { code: "RO", name: "Romania", lat: 45.9, lon: 24.9 },
  { code: "HU", name: "Hungary", lat: 47.2, lon: 19.5 },
  { code: "UA", name: "Ukraine", lat: 48.4, lon: 31.2 },
  { code: "RU", name: "Russia", lat: 55.8, lon: 56.6 },
  { code: "TR", name: "Türkiye", lat: 38.9, lon: 35.2 },
  { code: "IL", name: "Israel", lat: 31.0, lon: 34.9 },
  { code: "PS", name: "Palestine", lat: 31.9, lon: 35.2 },
  { code: "LB", name: "Lebanon", lat: 33.8, lon: 35.9 },
  { code: "EG", name: "Egypt", lat: 26.8, lon: 30.8 },
  { code: "SA", name: "Saudi Arabia", lat: 23.9, lon: 45.1 },
  { code: "AE", name: "United Arab Emirates", lat: 23.4, lon: 53.8 },
  { code: "IR", name: "Iran", lat: 32.4, lon: 53.7 },
  { code: "IQ", name: "Iraq", lat: 33.2, lon: 43.7 },
  { code: "PK", name: "Pakistan", lat: 30.4, lon: 69.3 },
  { code: "IN", name: "India", lat: 22.6, lon: 78.9 },
  { code: "BD", name: "Bangladesh", lat: 23.7, lon: 90.4 },
  { code: "LK", name: "Sri Lanka", lat: 7.9, lon: 80.8 },
  { code: "NP", name: "Nepal", lat: 28.4, lon: 84.1 },
  { code: "CN", name: "China", lat: 35.9, lon: 104.2 },
  { code: "JP", name: "Japan", lat: 36.2, lon: 138.3 },
  { code: "KR", name: "South Korea", lat: 35.9, lon: 127.8 },
  { code: "TW", name: "Taiwan", lat: 23.7, lon: 121.0 },
  { code: "HK", name: "Hong Kong", lat: 22.3, lon: 114.2 },
  { code: "PH", name: "Philippines", lat: 12.9, lon: 121.8 },
  { code: "VN", name: "Vietnam", lat: 14.1, lon: 108.3 },
  { code: "TH", name: "Thailand", lat: 15.9, lon: 101.0 },
  { code: "MY", name: "Malaysia", lat: 4.2, lon: 101.9 },
  { code: "SG", name: "Singapore", lat: 1.35, lon: 103.8 },
  { code: "ID", name: "Indonesia", lat: -2.5, lon: 118.0 },
  { code: "AU", name: "Australia", lat: -25.3, lon: 133.8 },
  { code: "NZ", name: "New Zealand", lat: -40.9, lon: 174.9 },
  { code: "ZA", name: "South Africa", lat: -30.6, lon: 22.9 },
  { code: "NG", name: "Nigeria", lat: 9.1, lon: 8.7 },
  { code: "KE", name: "Kenya", lat: -0.0, lon: 37.9 },
  { code: "ET", name: "Ethiopia", lat: 9.1, lon: 40.5 },
  { code: "GH", name: "Ghana", lat: 7.9, lon: -1.0 },
  { code: "MA", name: "Morocco", lat: 31.8, lon: -7.1 },
  { code: "DZ", name: "Algeria", lat: 28.0, lon: 1.7 },
  { code: "TN", name: "Tunisia", lat: 33.9, lon: 9.5 },
  { code: "IS", name: "Iceland", lat: 64.9, lon: -19.0 },
  { code: "EE", name: "Estonia", lat: 58.6, lon: 25.0 },
  { code: "LT", name: "Lithuania", lat: 55.2, lon: 23.9 },
  { code: "LV", name: "Latvia", lat: 56.9, lon: 24.6 },
];

export function findCountry(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}
